const NAV_ITEMS = [
  {
    id: "about",
    label: "About",
    icon: "about",
    to: "/membership",
    dropdownAlign: "left",
    dropdown: [
      { label: "About IEI", to: "/membership" },
      { label: "Engg Divisions", to: "/membership/info#engg-divisions" },
      { label: "IEI Council", to: "/membership/info#iei-council" },
      { label: "Policies and Regulations", to: "/membership/info#policies-regulations" },
      { label: "IEI Centres & Network", to: "/membership/info#iei-centres-network" },
      { label: "IEI Guest House", to: "/membership/info#iei-guest-house" },
      { label: "Tender Notice", to: "/membership/info#tender-notice" },
      { label: "Leadership", to: "/membership/info#leadership" },
      { label: "Career", to: "/membership/info#career" },
    ],
  },
  {
    id: "membership",
    label: "Membership",
    icon: "membership",
    to: "/membership/become-member",
    dropdownAlign: "left",
    dropdown: [
      { label: "Join IEI", to: "/membership/become-member" },
      { label: "Membership Benefits", to: "/membership/benefits" },
      { label: "Grades of Membership", to: "/membership/grades" },
      { label: "Upgrade Membership", to: "/membership/member-services#upgrade-membership" },
      { label: "Institutional Membership", to: "/membership/member-services#institutional-membership" },
      { label: "Fees and Subscription", to: "/membership/member-services#fees-subscriptions" },
      {
        label: "Student Chapters",
        dropdown: [
          { label: "Overview", to: "/membership/events-cpd#student-chapters" },
          { label: "Benefits", to: "/membership/events-cpd#student-chapter-benefits" },
          { label: "How to Join Student Chapter", to: "/membership/events-cpd#how-to-join-student-chapters" },
          { label: "Scholarship", to: "/membership/events-cpd#student-scholarship" },
          { label: "Student Directory", to: "/membership/events-cpd#student-directory" },
        ],
      },
      {
        label: "Search",
        dropdown: [
          { label: "Find a Member", to: "/membership/member-services#find-member" },
          { label: "Find Nearest Centre", to: "/membership/member-services#find-nearest-centre" },
          { label: "Practicing Chartered Engineer", to: "/membership/member-services#practicing-chartered-engineer" },
          { label: "Find Discrepancies", to: "/membership/member-services#find-discrepancies" },
          { label: "Check Despatch Status", to: "/membership/member-services#check-despatch-status" },
        ],
      },
      { label: "Announcement of Membership", to: "/membership/events-cpd#announcements" },
      { label: "FAQ", to: "/membership/member-services#faq" },
      { label: "Downloads", to: "/membership/info#downloads-forms" },
    ],
  },
  {
    id: "certification-arbitration",
    label: "Certification and Arbitration",
    icon: "certification",
    to: "/membership/certification",
    dropdownAlign: "left",
    dropdown: [
      { label: "Arbitration", to: "/membership/info#arbitration" },
      { label: "Chartered Engineers", to: "/membership/certification#chartered-engineer" },
      { label: "Professional Engineers", to: "/membership/certification#professional-engineer" },
      { label: "International Professional Engineers", to: "/membership/certification#international-professional-engineer" },
    ],
  },
  {
    id: "publication",
    label: "Publication",
    icon: "publication",
    to: "/membership/publications",
    dropdownAlign: "left",
    dropdown: [
      { label: "Journals", to: "/membership/publications#journals" },
      { label: "Books", to: "/membership/publications#books" },
      { label: "Proceedings", to: "/membership/publications#proceedings" },
      { label: "Compendium", to: "/membership/publications#compendium" },
      { label: "Annual Reports", to: "/membership/publications#annual-reports" },
      { label: "IEI News", to: "/membership/publications#iei-news" },
      { label: "IEI Epitome", to: "/membership/publications#iei-epitome" },
      { label: "Annual Technical Volume", to: "/membership/publications#annual-technical-volume" },
      { label: "Schedule and Rate", to: "/membership/publications#schedule-and-rate" },
    ],
  },
  {
    id: "technical-events",
    label: "Technical Events",
    icon: "events",
    to: "/membership/events-cpd",
    dropdownAlign: "left",
    dropdown: [
      { label: "Event Calendar", to: "/membership/events-cpd#event-calendar" },
      { label: "National Convention", to: "/membership/events-cpd#national-convention" },
      { label: "Seminar & Workshop", to: "/membership/events-cpd#seminar-workshop" },
      { label: "Webinar", to: "/membership/events-cpd#webinar" },
      { label: "Statutory Days", to: "/membership/events-cpd#statutory-days" },
      { label: "Technical Activity Guide Book", to: "/membership/events-cpd#technical-activity-guide-book" },
    ],
  },
  {
    id: "prize-awards",
    label: "Prize & Awards",
    icon: "awards",
    to: "/membership/info#prize-awards",
    dropdownAlign: "right",
    dropdown: [
      { label: "Industry Excellence Award", to: "/membership/info#industry-excellence-award" },
      { label: "Education Excellence Award", to: "/membership/info#education-excellence-award" },
      { label: "IEI Young Engineers Award", to: "/membership/info#iei-young-engineers-award" },
      { label: "Best Journal Prize", to: "/membership/info#best-journal-prize" },
      { label: "The SAIL Awards", to: "/membership/info#the-sail-awards" },
      { label: "NDRF Design Awards", to: "/membership/info#ndrf-design-awards" },
      { label: "The Coal India Awards", to: "/membership/info#the-coal-india-awards" },
    ],
  },
  {
    id: "research-grant",
    label: "Research Grant-in-Aid",
    icon: "research",
    to: "/membership/info#research-grant-in-aid",
    dropdownAlign: "right",
    dropdown: [
      { label: "Overview", to: "/membership/info#research-grant-overview" },
      { label: "Key Highlights", to: "/membership/info#research-grant-highlights" },
      { label: "Eligibility Criteria", to: "/membership/info#research-grant-eligibility" },
      { label: "How to Apply", to: "/membership/info#research-grant-apply" },
      { label: "Funded Projects", to: "/membership/info#research-grant-funded-projects" },
      { label: "R&D Compendium", to: "/membership/info#research-grant-rd-compendium" },
    ],
  },
  {
    id: "education-cpd",
    label: "Education and CPD",
    icon: "cpd",
    to: "/membership/events-cpd",
    dropdownAlign: "right",
    dropdown: [
      { label: "Academics", to: "/membership/events-cpd#academics" },
      { label: "Accreditation & Recognitions", to: "/membership/events-cpd#accreditation-recognitions" },
      { label: "Examination", to: "/membership/events-cpd#examination" },
      { label: "Continual Professional Development", to: "/membership/events-cpd#continual-professional-development" },
      { label: "Skill India Mission", to: "/membership/events-cpd#skill-india-mission" },
      { label: "Fees Structure", to: "/membership/events-cpd#fees-structure" },
      { label: "Downloads", to: "/membership/events-cpd#downloads" },
    ],
  },
];

export default NAV_ITEMS;
