const NAV_ITEMS = [
  {
    id: "about",
    label: "About",
    icon: "about",
    to: "/membership",
    dropdownAlign: "left",
    dropdown: [
      { label: "About IEI", to: "/membership" },
      { label: "Engg Divisions", to: "/membership/info#engg-divisions" },
      { label: "IEI Council", to: "/membership/info#iei-council" },
      { label: "Policies and Regulations", to: "/membership/info#policies-regulations" },
      { label: "IEI Centres & Network", to: "/membership/info#iei-centres-network" },
      { label: "IEI Guest House", to: "/membership/info#iei-guest-house" },
      { label: "Tender Notice", to: "/membership/info#tender-notice" },
      { label: "Leadership", to: "/membership/info#leadership" },
      { label: "Career", to: "/membership/info#career" },
    ],
  },
  {
    id: "membership",
    label: "Membership",
    icon: "membership",
    to: "/membership/become-member",
    dropdownAlign: "left",
    dropdown: [
      { label: "Membership Overview", to: "/membership" },
      { label: "Become a Member", to: "/membership/become-member" },
      { label: "Membership Types", to: "/membership/grades" },
      { label: "Subscription / Renewal", to: "/membership/member-services" },
      { label: "Downloads / Forms", to: "/membership/info#downloads-forms" },
      { label: "FAQ", to: "/membership/member-services" },
    ],
  },
  {
    id: "certification-arbitration",
    label: "Certification and Arbitration",
    icon: "certification",
    to: "/membership/certification",
    dropdownAlign: "left",
    dropdown: [
      { label: "Certification", to: "/membership/certification" },
      { label: "Arbitration", to: "/membership/info#arbitration" },
      { label: "Apply / Track", to: "/membership/certification" },
    ],
  },
  {
    id: "publication",
    label: "Publication",
    icon: "publication",
    to: "/membership/publications",
    dropdownAlign: "left",
    dropdown: [
      { label: "Journals", to: "/membership/publications" },
      { label: "Newsletters", to: "/membership/publications" },
      { label: "Proceedings", to: "/membership/publications" },
    ],
  },
  {
    id: "technical-events",
    label: "Technical Events",
    icon: "events",
    to: "/membership/events-cpd",
    dropdownAlign: "left",
    dropdown: [
      { label: "Upcoming Events", to: "/membership/events-cpd" },
      { label: "Conferences", to: "/membership/events-cpd" },
      { label: "Workshops / Seminars", to: "/membership/events-cpd" },
    ],
  },
  {
    id: "prize-awards",
    label: "Prize & Awards",
    icon: "awards",
    to: "/membership/info#prize-awards",
    dropdownAlign: "right",
    dropdown: [
      { label: "Award Categories", to: "/membership/info#award-categories" },
      { label: "Eligibility", to: "/membership/info#award-eligibility" },
      { label: "Nomination Process", to: "/membership/info#nomination-process" },
    ],
  },
  {
    id: "research-grant",
    label: "Research Grant-in-Aid",
    icon: "research",
    to: "/membership/info#research-grant-in-aid",
    dropdownAlign: "right",
    dropdown: [
      { label: "Scheme Details", to: "/membership/info#grant-scheme-details" },
      { label: "Apply", to: "/membership/info#grant-apply" },
      { label: "Status", to: "/membership/info#grant-status" },
    ],
  },
  {
    id: "education-cpd",
    label: "Education and CPD",
    icon: "cpd",
    to: "/membership/events-cpd",
    dropdownAlign: "right",
    dropdown: [
      { label: "CPD Programs", to: "/membership/events-cpd" },
      { label: "Courses", to: "/membership/events-cpd" },
      { label: "Registration", to: "/membership/events-cpd" },
    ],
  },
];

export default NAV_ITEMS;
